apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Name}}
  labels:
    group: {{.DeploymentGroupName}}
spec:
  replicas: {{.Replicas}}
  selector:
    matchLabels:
      group: {{.PodGroupName}}
  template:
    metadata:
      labels:
        group: {{.PodGroupName}}
    spec:
      containers:
      - image: registry.k8s.io/pause:3.9
        name: {{.Name}}
        resources:
          requests:
            cpu: {{.CpuRequest}}
            memory: {{.MemoryRequest}}
          limits:
            cpu: {{.CpuRequest}}
            memory: {{.MemoryRequest}}
